apiVersion: apps/v1beta1
kind: Deployment
metadata:
  initializers:
    pending: []
  labels:
    app: sops-operator
  name: sops-operator
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sops-operator
      name: sops-operator
    spec:
      serviceAccountName: sops-operator
      containers:
        - name: sops-operator
          image: spiddy/sops-operator:0.0.1
          imagePullPolicy: Always
