apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "sealedsecrets.harbur.io"
spec:
  group: "harbur.io"
  version: "v1alpha1"
  scope: "Namespaced"
  names:
    plural: "sealedsecrets"
    singular: "sealedsecret"
    kind: "SealedSecret"
  validation:
    openAPIV3Schema:
      required: ["data"]
